spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: itcast
  application:
    name: redis-demo
  #redis配置
  redis:
    cluster:
      nodes:
        - 192.168.211.132:7001
        - 192.168.211.132:7002
        - 192.168.211.132:7003
        - 192.168.211.132:7004
        - 192.168.211.132:7005
        - 192.168.211.132:7006
server:
  ssl:
    enabled: false
  port: 9008
mybatis:
  configuration:
    map-underscore-to-camel-case: true
